name: allerwise
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  cupertino_icons: ^1.0.2
  firebase_core: ^3.4.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  google_sign_in: ^6.2.1
  email_validator: ^2.1.17
  loading_indicator: ^3.1.1
  hugeicons: ^0.0.11
  flame: ^1.11.0
  provider: ^6.1.1
  speech_to_text: ^7.0.0
  flutter_tts: ^3.8.5
  http: ^1.1.0
  path_provider: ^2.1.1
  audioplayers: ^5.2.1
  table_calendar: ^3.0.9
  intl: ^0.19.0
  flutter_local_notifications: ^17.2.2
  android_alarm_manager_plus: ^4.0.3
  timezone: ^0.9.4
  permission_handler: ^11.3.1
  url_launcher: ^6.2.5
  mobile_scanner: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/characters/
    - assets/images/backgrounds/
    - assets/icons/
    - assets/data/
    - assets/data/scenarios/
    - assets/learn/
